# NumPy Library

In [2]:
import numpy as np

def fn_pm(mat):
    print(mat,'\n')
    

## The basics

In [122]:
a = np.array([1,2,3]) # integer arrray
print(a,'\n')

b= np.array([[1.2,1.5,1.6],[1.2,1.5,1.6]]) #float array
print(b,'\n')

# copy array with numpy 

c=b
print(c,'\n')
c[1]=100

print(b,'\n')

print(c,'\n')

d=b.copy()
d[1]=20
print(b,'\n')
print(c,'\n')
print(d,'\n')

[1 2 3] 

[[1.2 1.5 1.6]
 [1.2 1.5 1.6]] 

[[1.2 1.5 1.6]
 [1.2 1.5 1.6]] 

[[  1.2   1.5   1.6]
 [100.  100.  100. ]] 

[[  1.2   1.5   1.6]
 [100.  100.  100. ]] 

[[ 1.2  1.5  1.6]
 [20.  20.  20. ]] 

[[  1.2   1.5   1.6]
 [100.  100.  100. ]] 

[[  1.2   1.5   1.6]
 [100.  100.  100. ]] 



In [14]:
# get dimensions
print(a.ndim)
print(b.ndim)

# get shape
print(a.shape)
print(b.shape)

1
2
(3,)
(2, 3)


## Accesing, Changing

In [33]:
c= np.array([[1.2,1.5,1.6,1.7],[2.2,2.5,2.6,2.7]]) #float array
print(c) 

print(c.shape)

print(c[1,1]) # return a specific value [row, column]

print(c[0,:]) # all columns row 0

print(c[:,1]) # all rows column 1

print(c[0:2,0:2]) # submatrix

c[0,0]=2.5

print(c)

[[1.2 1.5 1.6 1.7]
 [2.2 2.5 2.6 2.7]]
(2, 4)
2.5
[1.2 1.5 1.6 1.7]
[1.5 2.5]
[[1.2 1.5]
 [2.2 2.5]]
[[2.5 1.5 1.6 1.7]
 [2.2 2.5 2.6 2.7]]


## 3D Array

In [40]:
d= np.array([[[1.2,1.5],[2.2,2.5]],[[3.6,3.7],[4.6,4.7]]]) #float array
print(d) 

[[[1.2 1.5]
  [2.2 2.5]]

 [[3.6 3.7]
  [4.6 4.7]]]


In [47]:
print(d[1,0,1]) # accessing [face,row,column]

3.7


## Initializing array

In [91]:
# matrix al zeros (face,row,column)
x1= np.zeros((3,3,3)) 
print(x1,'\n')

# matrix all ones (face,row,column)
x2= np.ones((2,2,4))
print(x2,'\n')

# new matrix all with the Number asign (dim(row,col),value)
x3 = np.full((2,2), 99) 
print(x3,'\n')

# new matrix with the same shape and repeted values (shape,value)
x4 = np.full_like(x3,4) 
print(x4,'\n')



[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]] 

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]] 

[[99 99]
 [99 99]] 

[[4 4]
 [4 4]] 

[[[0.28837997 0.32314889 0.88868175]
  [0.87348813 0.01414884 0.88908156]]

 [[0.17246698 0.85033761 0.70545411]
  [0.16481792 0.61570984 0.86340341]]] 



In [175]:
# identity matrix
x8=np.identity(3)
print(x8,'\n')

# repeat an array
x9=np.array([[1,2,3]])
x10=np.repeat(x9,3,axis=0)
print(x10,'\n')

# return a array from a list (start form 0 to 6 (excluyent de end))
x10 = np.arange(6)
fn_pm(x10)

# return a array from a list (start 'a' to end 'b' with a step 'c')
x10 = np.arange(-2,1,0.5)
fn_pm(x10)

# array of values equally distributed
x11= np.linspace(0,5,3)
fn_pm(x11)

[[0.13522574 0.47811296]
 [0.97015911 0.45590247]] 

[[[2 7 1]
  [3 5 1]
  [8 4 4]]

 [[9 6 9]
  [3 8 9]
  [6 2 8]]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1 2 3]
 [1 2 3]
 [1 2 3]] 

[0 1 2 3 4 5] 

[-2.  -1.5 -1.  -0.5  0.   0.5] 

[0.  2.5 5. ] 



## Example 

In [115]:
output=np.ones([5,5])
print(output,'\n')

temp=np.zeros([3,3])
temp[1,1]=9
print(temp,'\n')

output[1:4,1:4]=temp
print(output,'\n')

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]] 



## Reorganizing arrays

In [141]:
y1=np.array([[1,2,3,4],[4,5,6,7]])
print(y1,'\n')

y2=y1.reshape((4,2))
print(y2,'\n')

y3=y1.reshape((2,2,2)) # reshape values, take care of the data to fit on the deseare shape
print(y3,'\n')

#vertical stacking
v1,v2=np.array([1,2,3,4]),np.array([1,2,3,4])

v3=np.vstack([v1,v2])
print(v3,'\n')

#horizontal stacking
v4=np.hstack([v1,v2])
print(v4,'\n')


[[1 2 3 4]
 [4 5 6 7]] 

[[1 2]
 [3 4]
 [4 5]
 [6 7]] 

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]] 

[[1 2 3 4]
 [1 2 3 4]] 

[1 2 3 4 1 2 3 4] 



## Mathematics

In [4]:
a1=np.array([1,2,3,4])
fn_pm(a1)

#operations element wise
fn_pm(a1+2)
fn_pm(a1-2)
fn_pm(a1*2)
fn_pm(a1/2)
fn_pm(a1**2)

fn_pm(np.sin(a1))

[1 2 3 4] 

[3 4 5 6] 

[-1  0  1  2] 

[2 4 6 8] 

[0.5 1.  1.5 2. ] 

[ 1  4  9 16] 

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ] 



In [5]:
b1=np.array([4,5,6,7])
fn_pm(b1)

#operations element wise
fn_pm(a1+b1)
fn_pm(a1-b1)
fn_pm(a1*b1)
fn_pm(a1/b1)
fn_pm(a1**b1)

[4 5 6 7] 

[ 5  7  9 11] 

[-3 -3 -3 -3] 

[ 4 10 18 28] 

[0.25       0.4        0.5        0.57142857] 

[    1    32   729 16384] 



In [180]:
c1=np.array([[6,7],[4,5]])
fn_pm(c1)

fn_pm(np.sum(c1)) # all values
fn_pm(np.sum(c1,axis=0)) # sum by column
fn_pm(np.sum(c1,axis=1)) # sum by row



[[6 7]
 [4 5]] 

22 

[10 12] 

[13  9] 



## Linear Algebra

In [188]:
d1 = np.ones((2,3))
fn_pm(d1)

d2=np.full((3,2),2)
fn_pm(d2)

#matrix multiplication 
fn_pm(np.matmul(d1,d2))

#determinant 
d3=np.identity(3)
fn_pm(d3)
fn_pm(np.linalg.det(d3))


# new matrix 
d4=np.array([[0,1],[2,3]])
fn_pm(d4)

# transponse matrix (row to column, column to row)
d5=np.transpose(d4)
fn_pm(d5)

# inverse matrix 
d6=np.linalg.inv(d4)
fn_pm(d6)

# linear solver
b= np.array([[5],[7]])
fn_pm(b)

x=np.linalg.solve(d4,b)
fn_pm(x)

[[1. 1. 1.]
 [1. 1. 1.]] 

[[2 2]
 [2 2]
 [2 2]] 

[[6. 6.]
 [6. 6.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

1.0 

[[0 1]
 [2 3]] 

[[0 2]
 [1 3]] 

[[-1.5  0.5]
 [ 1.   0. ]] 

[[5]
 [7]] 

[[-4.]
 [ 5.]] 



## Random Modulus

In [191]:
# matrix of random numbers (face,row,columns)
x5=np.random.rand(2,2,3) 
print(x5,'\n')

# matrix with randoms number with the same shape of another matrix (matrix.shape)
x6=np.random.sample(x4.shape) 
print(x6,'\n')

# matrix with random integer numbers with size
x7=np.random.randint(1,10, size=(2,3,3))
print(x7,'\n')

# matrix from random numbers normally distributed
samples = np.random.normal(85, 10, size=(4,4))
fn_pm(samples)



[[[0.64564822 0.72071504 0.9314428 ]
  [0.13053559 0.2585445  0.17495943]]

 [[0.09289499 0.18891614 0.20511983]
  [0.60955307 0.96915445 0.20001426]]] 

[[0.04697774 0.09180442]
 [0.49610241 0.48773508]] 

[[[2 6 1]
  [3 3 5]
  [8 6 4]]

 [[1 6 4]
  [6 8 4]
  [5 2 6]]] 

[[77.54930523 78.74501669 88.37874729 81.909958  ]
 [83.28722269 92.31930185 71.00236867 77.56587541]
 [95.00691775 97.49648216 78.60197761 70.68858937]
 [85.46507481 83.28222781 75.11766936 85.10500063]] 



## Miscellaneous

### Data from file

In [144]:
filedata=np.genfromtxt('data.txt',delimiter=',')
print(filedata,'\n') #float for default

filedata_int=filedata.astype('int32')
print(filedata_int,'\n')

[[1. 2. 3. 4. 5.]
 [3. 4. 5. 6. 7.]
 [9. 7. 6. 5. 4.]] 

[[1 2 3 4 5]
 [3 4 5 6 7]
 [9 7 6 5 4]] 



### Boolean and indexing

In [146]:
DataRed=filedata[filedata>3]
print(DataRed,'\n')

[4. 5. 4. 5. 6. 7. 9. 7. 6. 5. 4.] 

